services:
  base_datos_mysql:
    image: mysql:8.0
    container_name: sprintdev_db_server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: spr1ntd3v_
      MYSQL_DATABASE: sprintdev_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: spr1ntd3v_
    ports:
      - "23306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: